
export enum CSV_TYPE {
    REQUESTS,ERRORS_BY_CLIENTID,ERRORS_SOC,USERS
}
export enum REQUEST_TYPE {
    STRONGBOX='STRONGBOX',
    HABILITATIONS='HABILITATIONS',
    USER_INFO_REQUEST='USER_INFO_REQUEST',
    LOGIN_ERROR='LOGIN_ERROR',
    CODE_TO_TOKEN='CODE_TO_TOKEN',
    LOGIN='LOGIN',
    REFRESH_TOKEN='REFRESH_TOKEN',
    CLIENT_LOGIN='CLIENT_LOGIN',
    RESET_PASSWORD_ERROR='RESET_PASSWORD_ERROR',
    TOKEN_EXCHANGE='TOKEN_EXCHANGE',
    UPDATE_PROFILE='UPDATE_PROFILE',
    REFRESH_TOKEN_ERROR='REFRESH_TOKEN_ERROR',
    CUSTOM_REQUIRED_ACTION_ERROR='CUSTOM_REQUIRED_ACTION_ERROR',
    CODE_TO_TOKEN_ERROR='CODE_TO_TOKEN_ERROR',
    SEND_RESET_PASSWORD_ERROR='SEND_RESET_PASSWORD_ERROR',
    SEND_VERIFY_EMAIL_ERROR='SEND_VERIFY_EMAIL_ERROR',
    UPDATE_PASSWORD='UPDATE_PASSWORD',
    LOGOUT='LOGOUT',
    CUSTOM_REQUIRED_ACTION='CUSTOM_REQUIRED_ACTION',
    VERIFY_EMAIL_ERROR='VERIFY_EMAIL_ERROR', //update 20 mai 2023
    SEND_RESET_PASSWORD='SEND_RESET_PASSWORD', //update 20 mai 2023
    UPDATE_PASSWORD_ERROR='UPDATE_PASSWORD_ERROR' //update 31 juillet 2023
}

export enum ERROR_BY_CLIENTID_TYPE{
    CLIENT_NOT_FOUND='CLIENT_NOT_FOUND',
    COOKIE='COOKIE',
    DIFF_USER_AUTH='DIFF_USER_AUTH',
    EXPIRED_CODE='EXPIRED_CODE',
    IDP_ERROR='IDP_ERROR',
    INVALID_CODE='INVALID_CODE',
    INVALID_REDIRECT_URI='INVALID_REDIRECT_URI',
    INVALID_USER_CRED='INVALID_USER_CRED',
    NOT_ALLOWED='NOT_ALLOWED',
    REQUEST_INVALID='REQUEST_INVALID',
    USER_DISABLED='USER_DISABLED',
    USER_NOT_FOUND='USER_NOT_FOUND',
    USER_DISABLED_TMP='USER_DISABLED_TMP',
    USERNAME_IN_USE='USERNAME_IN_USE'
}

export const ERROR_BY_CLIENTID_TYPE_HUMAN_READABLE_MAP:Map<string,ERROR_BY_CLIENTID_TYPE> = new Map([
    ['CLIENT NOT FOUND', ERROR_BY_CLIENTID_TYPE.CLIENT_NOT_FOUND],
    ['COOKIE', ERROR_BY_CLIENTID_TYPE.COOKIE],
    ['DIFFERENT USER AUTHENTICATED', ERROR_BY_CLIENTID_TYPE.DIFF_USER_AUTH],
    ['EXPIRED CODE', ERROR_BY_CLIENTID_TYPE.EXPIRED_CODE],
    ['IDENTITY PROVIDER ERROR', ERROR_BY_CLIENTID_TYPE.IDP_ERROR],
    ['INVALID CODE', ERROR_BY_CLIENTID_TYPE.INVALID_CODE],
    ['INVALID REDIRECT URI', ERROR_BY_CLIENTID_TYPE.INVALID_REDIRECT_URI],
    ['INVALID USER CREDENTIALS', ERROR_BY_CLIENTID_TYPE.INVALID_USER_CRED],
    ['NOT ALLOWED', ERROR_BY_CLIENTID_TYPE.NOT_ALLOWED],
    ['REQUÊTE INVALIDE', ERROR_BY_CLIENTID_TYPE.REQUEST_INVALID],
    ['USER DISABLED', ERROR_BY_CLIENTID_TYPE.USER_DISABLED],
    ['USER NOT FOUND', ERROR_BY_CLIENTID_TYPE.USER_NOT_FOUND],
    ['USER TEMPORARILY DISABLED', ERROR_BY_CLIENTID_TYPE.USER_DISABLED_TMP],
    ['USERNAME IN USE', ERROR_BY_CLIENTID_TYPE.USERNAME_IN_USE],
])

export enum ERROR_SOC_TYPE{
    SGMC='SGMC',
    FMC='FMC',
    NOT_AUTHORIZED='Non autorisé',
    WRONG_PASSWORD='Mauvais mot de passe',
    ACCOUNT_BLOCKED='Compte bloqué',
    WRONG_TIPING='Mauvaise saisie',
    WRONG_ROYAUME='Mauvais royaume -_-',
    PASSWORD_EXPIRED='Mot de passe expiré',
    USER_NEVER_CONNECTED='Utilisateur jamais connecté',
    BANQUE_ERR_UNKNOWN='Banque ??'
}

export interface minMax{
    min:number,
    max:number
}
